export const S = {
  appName: 'Spine Check',
  runtime: (v: string) => `runtime ${v}`,
  add: 'Add',
  report: 'Report',
  settings: 'Settings',
  clearAll: 'Clear all',
  busy: 'analysing…',
  dropTitle: 'Drop the delivery folder, or the .json/.skel, .atlas and image files',
  dropHint: '@0.5x subfolders become variants. Nothing leaves your computer.',
  selectFolder: 'Select folder',
  selectFiles: 'Select files',
  loadSample: 'Load sample',
  ignored: (n: number) => `${n} file(s) ignored`,
  status: { pending: 'queued', checking: 'checking', loading: 'loading', probing: 'probing', done: 'done' } as const,
  tabs: { findings: 'Findings', details: 'Details' },
  views: { bundles: 'Bundles', preview: 'Preview', findings: 'Findings', details: 'Details' },
  sev: { error: 'Errors', warning: 'Warnings', info: 'Info' } as const,
  search: 'Search…',
  noFindings: 'No findings match this filter.',
  hint: 'Hint',
  preview: {
    animation: 'Animation', skin: 'Skin', loop: 'Loop', speed: 'Speed',
    fit: 'Fit (F)', zoomIn: 'Zoom in', zoomOut: 'Zoom out',
    bg: { dark: 'Dark', light: 'Light', checker: 'Checker' },
    pma: 'PMA', grid: 'Grid', overlays: 'Overlays', close: 'Done',
    capture: 'Capture PNG', record: 'Record WebM', stopRecord: 'Stop recording',
    play: 'Play (Space)', pause: 'Pause (Space)',
    root: 'root', variant: 'Variant',
    noRuntime: 'The runtime could not load this bundle. See the errors under Findings.',
    empty: 'Select a bundle from the list.',
    pending: 'Analysing…',
  },
  overlays: {
    bones: 'Bones', regions: 'Regions', meshHull: 'Mesh hull', meshTriangles: 'Mesh triangles',
    boundingBoxes: 'Bounding boxes', paths: 'Paths', clipping: 'Clipping',
    skeletonSize: 'Declared size', animationBounds: 'Animation bounds', grid: 'Grid',
  },
  sequence: { title: 'Sequence', add: 'Add clip', play: 'Play sequence', stop: 'Stop', mix: 'Mix (s)', hold: 'Hold (s)', loop: 'Loop', remove: 'Remove', up: 'Move up', down: 'Move down', total: 'total' },
  details: {
    skeleton: 'Skeleton', version: 'Version', hash: 'Hash', size: 'Declared size', bones: 'Bones', slots: 'Slots', skins: 'Skins',
    animations: 'Animations', events: 'Events', pages: 'Atlas pages', duration: 'Duration', seamless: 'Seamless loop', bounds: 'Bounds (w×h)',
    slot: 'Slot', bone: 'Bone', attachment: 'Setup attachment', blend: 'Blend', page: 'Page', dims: 'Size', declared: 'Declared',
    format: 'Format', bytes: 'Bytes', pma: 'PMA', scale: 'Scale', runtime: 'Runtime',
    loadedIn: (ms: number) => `loaded in ${Math.round(ms)} ms`, failed: 'failed', none: '—', yes: 'yes', no: 'no',
  },
  reportDialog: { title: 'Report', markdown: 'Markdown', json: 'JSON', copy: 'Copy', copied: 'Copied!', download: 'Download', close: 'Close' },
  settingsDialog: {
    title: 'Settings', reset: 'Restore defaults', save: 'Save and re-analyse', cancel: 'Cancel',
    fields: {
      runtimeVersion: 'Target runtime version (major.minor)',
      pageMaxWarn: 'Page: warn above (px)',
      pageMaxError: 'Page: error above (px)',
      pagesWarn: 'Warn above N pages',
      occupancyWarn: 'Minimum atlas occupancy (0–1)',
      pngWarnBytes: 'PNG: suggest WebP above (bytes)',
      gpuMemoryWarnBytes: 'Texture memory: warn above (bytes)',
      meshVerticesWarn: 'Mesh: warn above N vertices',
      trianglesWarn: 'Total triangles: warn above',
      deformWarn: 'Deform timelines: info above',
      skeletonSizeWarn: 'Skeleton size: warn above (px)',
      suspiciousPatterns: 'Suspicious name patterns (comma-separated)',
      probeMaxSteps: 'Maximum probe steps',
    } as const,
  },
}
