export const S = {
  appName: 'Spine Check',
  runtime: (v: string) => `runtime ${v}`,
  add: 'Adicionar',
  report: 'Relatório',
  settings: 'Configurações',
  clearAll: 'Limpar tudo',
  busy: 'analisando…',
  dropTitle: 'Arraste a pasta da entrega ou os arquivos .json/.skel, .atlas e imagens',
  dropHint: 'Subpastas @0.5x viram variantes. Nada sai do seu computador.',
  selectFolder: 'Selecionar pasta',
  selectFiles: 'Selecionar arquivos',
  loadSample: 'Carregar exemplo',
  ignored: (n: number) => `${n} arquivo(s) ignorado(s)`,
  status: { pending: 'na fila', checking: 'checando', loading: 'carregando', probing: 'sondando', done: 'pronto' } as const,
  tabs: { findings: 'Findings', details: 'Detalhes' },
  views: { bundles: 'Bundles', preview: 'Preview', findings: 'Findings', details: 'Detalhes' } as const,
  sev: { error: 'Erros', warning: 'Avisos', info: 'Info' } as const,
  search: 'Buscar…',
  noFindings: 'Nenhum finding com esse filtro.',
  hint: 'Dica',
  preview: {
    animation: 'Animação', skin: 'Skin', loop: 'Loop', speed: 'Velocidade',
    fit: 'Enquadrar (F)', zoomIn: 'Aproximar', zoomOut: 'Afastar',
    bg: { dark: 'Escuro', light: 'Claro', checker: 'Xadrez' },
    pma: 'PMA', grid: 'Grade', overlays: 'Overlays',
    capture: 'Capturar PNG', record: 'Gravar WebM', stopRecord: 'Parar gravação',
    play: 'Tocar (Espaço)', pause: 'Pausar (Espaço)',
    root: 'raiz', variant: 'Variante',
    noRuntime: 'O runtime não carregou este bundle. Veja os erros em Findings.',
    empty: 'Selecione um bundle na lista.',
    pending: 'Analisando…',
  },
  overlays: {
    bones: 'Bones', regions: 'Regions', meshHull: 'Mesh hull', meshTriangles: 'Mesh triângulos',
    boundingBoxes: 'Bounding boxes', paths: 'Paths', clipping: 'Clipping',
    skeletonSize: 'Tamanho declarado', animationBounds: 'Bounds da animação', grid: 'Grade',
  },
  sequence: { title: 'Sequência', add: 'Adicionar clipe', play: 'Tocar sequência', stop: 'Parar', mix: 'Mix (s)', hold: 'Hold (s)', loop: 'Loop', remove: 'Remover', up: 'Subir', down: 'Descer', total: 'total' },
  details: {
    skeleton: 'Skeleton', version: 'Versão', hash: 'Hash', size: 'Tamanho declarado', bones: 'Bones', slots: 'Slots', skins: 'Skins',
    animations: 'Animações', events: 'Eventos', pages: 'Páginas do atlas', duration: 'Duração', seamless: 'Loop seamless', bounds: 'Bounds (w×h)',
    slot: 'Slot', bone: 'Bone', attachment: 'Attachment de setup', blend: 'Blend', page: 'Página', dims: 'Dimensões', declared: 'Declarado',
    format: 'Formato', bytes: 'Tamanho', pma: 'PMA', scale: 'Scale', runtime: 'Runtime',
    loadedIn: (ms: number) => `carregou em ${Math.round(ms)} ms`, failed: 'falhou', none: '—', yes: 'sim', no: 'não',
  },
  reportDialog: { title: 'Relatório', markdown: 'Markdown', json: 'JSON', copy: 'Copiar', copied: 'Copiado!', download: 'Baixar', close: 'Fechar' },
  settingsDialog: {
    title: 'Configurações', reset: 'Restaurar padrões', save: 'Salvar e reanalisar', cancel: 'Cancelar',
    fields: {
      runtimeVersion: 'Versão do runtime alvo (major.minor)',
      pageMaxWarn: 'Página: aviso acima de (px)',
      pageMaxError: 'Página: erro acima de (px)',
      pagesWarn: 'Aviso acima de N páginas',
      occupancyWarn: 'Ocupação mínima do atlas (0–1)',
      pngWarnBytes: 'PNG: sugerir WebP acima de (bytes)',
      gpuMemoryWarnBytes: 'Memória de textura: aviso acima de (bytes)',
      meshVerticesWarn: 'Mesh: aviso acima de N vértices',
      trianglesWarn: 'Triângulos totais: aviso acima de',
      deformWarn: 'Deform timelines: info acima de',
      skeletonSizeWarn: 'Tamanho do skeleton: aviso acima de (px)',
      suspiciousPatterns: 'Padrões de nome suspeito (separados por vírgula)',
      probeMaxSteps: 'Passos máximos da sonda',
    } as const,
  },
}
